### ISSUE TITLE
more lasers; fireballs

### ISSUE THREAD

**Issue by WyattHRichter** [cormac-obrien/richter#12]
this engine is severely lacking the ability to create lasers. I am also disappointed in the lack of any fireball functionality. good luck marketing this engine to any gamedevs in 2018.

**Comment by cormac-obrien** [comment]
I can proudly say that Richter now supports lasers:

![richter-2020-07-17T22-48-07](https://user-images.githubusercontent.com/5809282/87836462-c3bde980-c855-11ea-8680-32449d5431c9.png)

as well as fireballs:

![richter-2020-07-17T22-47-43](https://user-images.githubusercontent.com/5809282/87836466-c91b3400-c855-11ea-9f20-58c0e35e5222.png)

as of the latest update, and so this issue can be closed!

**Comment by WyattHRichter** [comment]
finally! now this engine is going places! watch out, unreal!
