### ISSUE TITLE
Could not build shaders :   cmake missing 

### ISSUE THREAD

**Issue by ethereumdegen** [cormac-obrien/richter#52]
On ubuntu, cloned devel and ran 'cargo build'. Got this : 

The following warnings were emitted during compilation:

warning: Checking for system installed libraries.  Use --features = build-from-source to disable this behavior
warning: System installed library not found.  Falling back to build from source

error: failed to run custom build command for `shaderc-sys v0.6.3`

Caused by:
  process didn't exit successfully: `/home/andy/rust/richter/target/debug/build/shaderc-sys-f89ed4c0ddc2d59e/build-script-build` (exit status: 101)
  --- stdout
  cargo:warning=Checking for system installed libraries.  Use --features = build-from-source to disable this behavior
  cargo:warning=System installed library not found.  Falling back to build from source

  --- stderr
  thread 'main' panicked at '

  couldn't find required command: "cmake"

**Comment by apexmfer** [comment]
Strangely, i seem to have cmake.   'apt show cmake' returns this 

Package: cmake
Version: 3.16.3-1ubuntu1
Priority: optional
Section: devel
Origin: Ubuntu

**Comment by ethereumdegen** [comment]
sudo apt install cmake

worked!  

However i wish this wasnt a dependency.  seems like python is a dependency too. ugh
