### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [cormac-obrien/richter#6]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Looks like this is blocked by https://github.com/docopt/docopt.rs/issues/128. I will follow up in this issue when they have a new release ready.

**Comment by cormac-obrien** [comment]
Thanks for the update, I'll keep an eye out.
